FROM node:23-alpine AS build

WORKDIR /dist/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=production
RUN npm run build --prod

FROM nginx:alpine

ENV TZ=America/Guatemala
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY --from=build /dist/src/app/dist /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80