FROM node:22-alpine AS build
ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./

RUN npm install

FROM node:22-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY --from=build /app .

COPY . .

EXPOSE 5000
ENV TZ=America/Guatemala

CMD ["src/index.js"]
