FROM node:21-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install -g nodemon 
RUN npm audit fix --force

COPY . .

EXPOSE 5000
ENV TZ=America/Guatemala

CMD ["nodemon", "src/index.js"]
